apiVersion: v1
kind: Service
metadata:
  name: chatbot-todo-service
  labels:
    app: chatbot-todo-app
spec:
  type: NodePort
  selector:
    app: chatbot-todo-app
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
      protocol: TCP
      name: http
